/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as TrendsRouteImport } from './routes/trends'
import { Route as PortfoliosRouteImport } from './routes/portfolios'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TickerProfileSymbolRouteImport } from './routes/ticker-profile.$symbol'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendsRoute = TrendsRouteImport.update({
  id: '/trends',
  path: '/trends',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfoliosRoute = PortfoliosRouteImport.update({
  id: '/portfolios',
  path: '/portfolios',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TickerProfileSymbolRoute = TickerProfileSymbolRouteImport.update({
  id: '/ticker-profile/$symbol',
  path: '/ticker-profile/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portfolios': typeof PortfoliosRoute
  '/trends': typeof TrendsRoute
  '/watchlist': typeof WatchlistRoute
  '/ticker-profile/$symbol': typeof TickerProfileSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portfolios': typeof PortfoliosRoute
  '/trends': typeof TrendsRoute
  '/watchlist': typeof WatchlistRoute
  '/ticker-profile/$symbol': typeof TickerProfileSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/portfolios': typeof PortfoliosRoute
  '/trends': typeof TrendsRoute
  '/watchlist': typeof WatchlistRoute
  '/ticker-profile/$symbol': typeof TickerProfileSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/portfolios'
    | '/trends'
    | '/watchlist'
    | '/ticker-profile/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/portfolios'
    | '/trends'
    | '/watchlist'
    | '/ticker-profile/$symbol'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/portfolios'
    | '/trends'
    | '/watchlist'
    | '/ticker-profile/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  PortfoliosRoute: typeof PortfoliosRoute
  TrendsRoute: typeof TrendsRoute
  WatchlistRoute: typeof WatchlistRoute
  TickerProfileSymbolRoute: typeof TickerProfileSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trends': {
      id: '/trends'
      path: '/trends'
      fullPath: '/trends'
      preLoaderRoute: typeof TrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolios': {
      id: '/portfolios'
      path: '/portfolios'
      fullPath: '/portfolios'
      preLoaderRoute: typeof PortfoliosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ticker-profile/$symbol': {
      id: '/ticker-profile/$symbol'
      path: '/ticker-profile/$symbol'
      fullPath: '/ticker-profile/$symbol'
      preLoaderRoute: typeof TickerProfileSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  PortfoliosRoute: PortfoliosRoute,
  TrendsRoute: TrendsRoute,
  WatchlistRoute: WatchlistRoute,
  TickerProfileSymbolRoute: TickerProfileSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
